apply plugin: 'base'

buildscript {
     repositories {
         google()
         mavenCentral()
     }
     dependencies {
         classpath "com.android.tools.build:gradle:8.4.0"

         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
     }
 }

configurations {
    azureCalling
    azureCommon
    azureCore
    azureCoreLogging
    trouterClient
}

dependencies {
    azureCalling 'com.azure.android:azure-communication-calling:2.16.0'
    azureCommon 'com.azure.android:azure-communication-common:1.2.1'
    azureCore 'com.azure.android:azure-core:1.0.0-beta.14'
    azureCoreLogging 'com.azure.android:azure-core-logging:1.0.0-beta.14'
    trouterClient 'com.microsoft:trouter-client-android:1.0.0'
}

task downloadAzureCalling(type: Copy) {
    from configurations.azureCalling 
    into 'Laerdal.Maui.AzureCommunicationCalling.Android/Jars'
}
task downloadAzureCommon(type: Copy) {
    from configurations.azureCommon 
    into 'Laerdal.Maui.AzureCommunicationCommon.Android/Jars'
}
task downloadAzureCore(type: Copy) {
    from configurations.azureCore 
    into 'Laerdal.Maui.AzureCore.Android/Jars'
}
task downloadAzureCoreLogging(type: Copy) {
    from configurations.azureCoreLogging 
    into 'Laerdal.Maui.AzureCoreLogging.Android/Jars'
}
task downloadTrouterClient(type: Copy) {
    from configurations.trouterClient 
    into 'Laerdal.Maui.TrouterClient.Android/Jars'
}
