source 'https://github.com/CocoaPods/Specs.git' 

plugin 'cocoapods-binary'
platform :ios, '14.0'
use_frameworks!

target 'nativeLibsPlaceholder' do
   pod 'AzureCommunicationCalling', '~> 2.11.0', :binary => true
end
