plugin 'cocoapods-binary'
platform :ios, '12.0'
use_frameworks!

target 'nativeLibsPlaceholder' do
  pod 'AzureCommunicationCalling', '~> 1.0.0-beta.8'
  pod 'AzureCommunication', '~> 1.0.0-beta.8', :binary => true
  pod 'AzureCore', '~> 1.0.0-beta.8', :binary => true
end
