plugin 'cocoapods-binary'
platform :ios, '12.0'
use_frameworks!

target 'nativeLibsPlaceholder' do
   pod 'AzureCommunicationCalling', '~> 1.1.0', :binary => true
   pod 'AzureCore', '~> 1.0.0-beta.13', :binary => true
end
