<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <PackageId>Laerdal.Maui.TrouterClient.android</PackageId>
      <version>1.0.0.0</version>
      <TargetFrameworks>net9.0-android</TargetFrameworks>
      <Nullable>enable</Nullable>
      <ImplicitUsings>true</ImplicitUsings>
      <IsBindingProject>true</IsBindingProject>
      <AssemblyName>Laerdal.Maui.TrouterClient.Android</AssemblyName>
      <Title>TrouterClient for net</Title>
      <Authors>Laerdal Medical</Authors>
      <Description>
          Binding for Microsoft Trouter Client for Android.
      </Description>
      <PackagesReleaseNotes>
          1.0.0.0
      </PackagesReleaseNotes>
      <Copyright>Copyright Laerdal Medical 2025</Copyright>
      <RepositoryUrl>https://github.com/laerdal/Xamarin.AzureCommunicationCalling</RepositoryUrl>
      <ProjectUrl>https://github.com/laerdal/Xamarin.AzureCommunicationCalling</ProjectUrl>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageTags>Maui Azure Android</PackageTags>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup>
      <AndroidLibrary Update="Jars\trouter-client-android-1.0.0.aar">
        <Bind>false</Bind>
      </AndroidLibrary>
    </ItemGroup>
</Project>
